apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://codeup.aliyun.com/616a7ea7ea46a7508ba91d44/KubeVela-demo-CICD-app
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: prod
      path: ./apps
